POST https://nodejs-video-api-51qq.onrender.com/videos
Content-Type: application/json
Accept-Language: pt


{
  "title": "Video node 05",
  "description": "Esse é o video 05",
  "duration": 310
}


###


GET https://nodejs-video-api-51qq.onrender.com/videos?search


###

PUT https://nodejs-video-api-51qq.onrender.com/videos/bbe44194-5e92-4ee0-a862-41f6fdaee996
Content-Type: application/json
Accept-Language: pt


{
  "title": "Video node 05",
  "description": "Esse é o video 05",
  "duration": 510
}


###


DELETE https://nodejs-video-api-51qq.onrender.com/videos/bbe44194-5e92-4ee0-a862-41f6fdaee996